app/auth/routes.py, app/models.py, scripts/view_databases.py
Create a function that assign conditions to users dynamically
=> Assign conditions

app/auth/routes.py, app/main/routes.py, app/templates/main/explain_A.html, app/templates/main/explain_B.html, app/templates/main/explain_C.html
Redirect to multiple explain pages
=> Redirect to multiple explain page

app/main/routes.py, app/templates/main/lifestyle.html
Update lifestyle.html : 
- Add 3 options group questions : scroll, likert and cursor
- Check that all questions are answerd
Update routes.py:
- Extract questions for lifestyle questionnaire, with question.form_id in addition to what is done for satisfaction route
=> Lifestyle questionnaire

app/main/routes.py, app/templates/main/lifestyle.html, app/templates/main/satisfaction.html
In routes.py:
- Extract values from lifestyle in explain route
- Log values in db
- Fix issue that for cursor the answer_content was logged instead of answer_id
Clean comments on files
=> Log lifestyle answers

Makefile, app/main/routes.py, app/ml/crossval.py, app/ml/deploy.py, app/ml/feature_engineering.py, app/ml/feature_selection.py, app/ml/loaders.py, app/ml/metrics.py, app/ml/models.py, app/ml/sandbox.py, app/ml/test.py, app/ml/tracking.py, app/ml/utils.py
Packaging:
- Update Makefile for running .py files in ml folder
- Modify import of functions in .py files of ml folder
Prepare predict in website:
- Save answers of lifestyle in a dataframe
=> Packaging and prepare predict

app/templates/main/lifestyle.html
In lifestyle.html:
- Add checkbox option for questions
- Verify in the script that we have at least 1 answer for the question
=> Add checkbox in lifestyle questions

app/main/routes.py, app/static/css/style.css, app/templates/main/essaim.html, app/templates/main/intent.html, app/templates/main/knowledge.html, app/templates/main/knowledge_after.html, app/templates/main/knowledge_before.html, app/templates/main/lifestyle.html, app/templates/main/likert_table.html, app/templates/main/satisfaction.html
This is work in progress, do not merge ! 
I am attempting to improve the style of likert scale.
This is hard as I am trying to merge similar likert-scale structure together into consistent tables.
=> Improve likert design

app/main/routes.py, app/static/css/style.css, app/templates/main/consent.html, app/templates/main/explain_baseline.html, app/templates/main/explain_interactive.html, app/templates/main/explain_quantitative.html, app/templates/main/explain_textual.html, app/templates/main/explain_visual.html, app/templates/main/lifestyle.html
- buttons -> red
- solve radar chart
- remove bold from questions
=> Uniformize design

app/main/routes.py, app/templates/main/explain_interactive.html, config.py
- Remember last questions answered and display
- Interactive page prepared on 5 featured questions
=> Explain interactive mvp

Makefile, app/models.py, scripts/reload_experiment.py, scripts/view_databases.py
In models.py:
- create UserPII class
- remove email and interac from User class
- create one-to-one relationship between User and UserPII
In view_databases.py:
- create display_userpiis():
In reload_experiment.py:
- populate UserPII
In Makefile:
- add make display-userpiis
=> Create UserPII table

app/templates/main/intent.html, app/templates/main/question_blocs.html
Add intention questions and adapt likert scales to it.
=> Intention questions

app/main/routes.py
The form_id wasn't updated during explain interactive
=> Bug resolution

app/templates/main/explain_baseline.html, app/templates/main/explain_quantitative.html, app/templates/main/explain_textual.html
=> Explain baseline

app/main/routes.py, app/templates/main/explain_quantitative.html
When we did a new  explain, it kept the previous feature_content_dic and added several times feature_coeff and values_coeff. So create a function to create a new dic for each new explain.
+ Change description for explain quanti
=> Fix issue with feature_content_dic for explain

Makefile, app/ml/configs/eda.py, app/ml/eda.py
create eda.py that compute the quartiles for target score
create config for eda aligned with config of crossval
create a command make to compute quartiles: make eda
=> compute quartiles

app/templates/main/explain_contextual.html, config.py
Create explain contextual with quartiles of distribution
=> Add explain contextual

app/static/css/style.css
Had to find a solution with rem instead of em, so had to play a bit manually
=> Issue Row 2 - Adjust list size

app/main/routes.py, app/templates/main/explain_interactive.html
Explain interactive : 
- now has a context to explain to the user how he can play with the system
- show the score increase by contrasting it to previous score
=> Issue row25 26 explain interactive

app/templates/main/explain_contextual.html, app/templates/main/explain_quantitative.html, app/templates/main/explain_textual.html, app/templates/main/explain_visual.html
=> Fvv explain intro

app/auth/routes.py, app/main/routes.py, app/templates/main/merci.html, app/templates/main/prolific_redirect.html, config.py
- identification with a prolific_id
- redirection at the end of the study to the prolific page with the completion code (to adjust in the config)
=> Prolific integration

scripts/streamlit_logs.py
update visualization of user approval on streamlit
=> User approbation streamlit

Makefile, scripts/results_analyses.py
create 2 make : 
- filter-results: it reads the db from the selected batch (entered manually at the beginning of the results_analyses.py file), filter users and logs to keep only those of approved users who passed the 2 attention checks, and write the filtered db in the clean folder
- clean-results: it create a new csv with the results necessary for the statistical analyses, this csv file is called "clean_results" and is save in the clean folder
The codebook of the clean_results.csv is available on the clean folder of the Dropbox.
=> Clean results
